const $=id=>document.getElementById(id), audio=$('audio');
const album=await fetch('album.json').then(r=>{if(!r.ok)throw Error('Album unavailable');return r.json()});

const storageKey=album.id; let decisions={},active=null,take=null,loadToken=0;
const time=n=>`${Math.floor((n||0)/60)}:${String(Math.floor((n||0)%60)).padStart(2,'0')}`;
function validate(data){if(data.album_id!==album.id)throw Error('This review belongs to a different album.');const clean={};for(const t of album.tracks){const d=data.decisions?.[t.id];if(!d)continue;if(d.take_id && !t.takes.some(x=>x.id===d.take_id))throw Error('Unrecognized take.');clean[t.id]={take_id:d.take_id||null,redo:!!d.redo,note:String(d.note||'').slice(0,1500)};}return clean;}
try{const saved=JSON.parse(localStorage.getItem(storageKey)||'null');if(saved)decisions=validate(saved);}catch{}
const encode=data=>btoa(Array.from(new TextEncoder().encode(JSON.stringify(data)),b=>String.fromCharCode(b)).join(''));
const decode=text=>JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(text),c=>c.charCodeAt(0))));
function packet(){return{schema:'voxxora.take-review.v1',album_id:album.id,artist:album.artist,album:album.title,created_at:new Date().toISOString(),provisional:true,cleanup_authorized:false,decisions,selected_takes:album.tracks.flatMap(t=>{const x=t.takes.find(x=>x.id===decisions[t.id]?.take_id);return x?[{track:t.title,flow_id:x.id,label:x.label,wav_sha256:x.wav_sha256,source_sha256:x.source_sha256,preview_sha256:x.preview_sha256,lyrics_sha256:x.lyrics_sha256}]:[]})};}
if(location.hash.startsWith('#review=')){try{decisions=validate(decode(location.hash.slice(8)));$('saveState').textContent='Opened shared choices. These are provisional and have not changed studio masters.';}catch(e){$('saveState').textContent='Cannot open shared review: '+e.message;}}
function save(){try{localStorage.setItem(storageKey,JSON.stringify(packet()));}catch{$('saveState').textContent='Device storage is unavailable. Export or share your choices before leaving.';}renderSongs();}
function decision(track){return decisions[track.id]||(decisions[track.id]={take_id:null,redo:false,note:''});}
function renderSongs(){$('songs').replaceChildren();for(const t of album.tracks){const b=document.createElement('button');b.className='song'+(active?.id===t.id?' active':'')+(active?.id===t.id&&!audio.paused?' playing':'');b.setAttribute('aria-label',`Listen to ${t.title}`);const n=document.createElement('span');n.className='num';n.textContent=t.id;const name=document.createElement('strong');name.textContent=t.title;const d=document.createElement('span');d.className='decision';const choice=t.takes.find(x=>x.id===decisions[t.id]?.take_id);d.textContent=choice?'♥ '+choice.label:decisions[t.id]?.redo?'New takes requested':t.takes.length?`${t.takes.length} takes`:'Awaiting audio';b.append(n,name,d);b.disabled=!t.takes.length;b.onclick=()=>openSong(t);$('songs').append(b);}$('progress').textContent=`${album.tracks.filter(t=>decisions[t.id]?.take_id||decisions[t.id]?.redo).length} / ${album.tracks.length} reviewed`;}
function openSong(t){active=t;$('dock').hidden=false;$('current').textContent=t.title;$('notes').disabled=false;$('notes').value=decisions[t.id]?.note||'';$('notes').placeholder='What worked? What would you change?';selectTake(t.takes[0]);}
function renderTakes(){$('takes').replaceChildren();for(const x of active.takes){const lane=document.createElement('div');lane.className='take'+(decisions[active.id]?.take_id===x.id?' selected':'')+(take?.id===x.id?' current':'')+(take?.id===x.id&&!audio.paused?' playing':'');const b=document.createElement('button');b.className='choose';b.textContent=x.label;const s=document.createElement('small');s.textContent=time(x.duration);b.append(s);b.onclick=()=>selectTake(x);const h=document.createElement('button');h.className='heart';h.textContent=decisions[active.id]?.take_id===x.id?'♥':'♡';h.setAttribute('aria-label','Prefer '+active.title+' '+x.label);h.setAttribute('aria-pressed',String(decisions[active.id]?.take_id===x.id));h.onclick=()=>{const d=decision(active);d.take_id=d.take_id===x.id?null:x.id;d.redo=false;save();renderTakes();};lane.append(b,h);$('takes').append(lane);}$('redo').setAttribute('aria-pressed',String(!!decisions[active.id]?.redo));}
async function selectTake(x){const token=++loadToken;audio.pause();take=x;audio.src=x.src;$('lyricsLink').href=x.lyrics_src||'#';audio.currentTime=0;$('duration').textContent=time(x.duration);$('status').textContent='Loading '+x.label+'…';renderTakes();renderSongs();try{await audio.play();if(token===loadToken)$('status').textContent=x.label+' · '+album.format;}catch(e){if(token===loadToken&&e.name!=='AbortError')$('status').textContent='Tap Play to start, or try another take if loading fails.';}}
audio.onplay=()=>{$('play').textContent='Ⅱ';$('play').setAttribute('aria-label','Pause');renderTakes();renderSongs();};audio.onpause=()=>{$('play').textContent='▶';$('play').setAttribute('aria-label','Play');if(active)renderTakes();renderSongs();};audio.onerror=()=>{$('status').textContent='Audio could not load. Check your connection and tap Play to retry.';};
audio.ontimeupdate=()=>{const ratio=audio.duration?audio.currentTime/audio.duration:0;$('seek').value=String(ratio*1000);$('fill').style.width=ratio*100+'%';$('elapsed').textContent=time(audio.currentTime);};
$('seek').oninput=()=>{if(Number.isFinite(audio.duration))audio.currentTime=Number($('seek').value)/1000*audio.duration;};
$('play').onclick=()=>{if(!take)return;if(audio.paused)audio.play().catch(()=>{$('status').textContent='Playback failed. Please try again.';});else audio.pause();};$('stop').onclick=()=>{audio.pause();audio.currentTime=0;};
$('redo').onclick=()=>{if(!active)return;const d=decision(active);d.redo=!d.redo;d.take_id=null;save();renderTakes();$('status').textContent=d.redo?'New takes requested. Existing recordings are untouched.':'Request cleared.';};
$('notes').oninput=()=>{if(active){decision(active).note=$('notes').value;save();}};
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&!e.target.closest('button,input,textarea,a,dialog')&&take){e.preventDefault();$('play').click();}});
$('share').onclick=()=>{const p={album_id:album.id,decisions};$('resultLink').value=location.origin+location.pathname+'#review='+encode(p);$('shareDialog').showModal();};$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('resultLink').value);$('copy').textContent='Copied';}catch{$('resultLink').select();$('copy').textContent='Select and copy link';}};$('nativeShare').onclick=async()=>{if(navigator.share){try{await navigator.share({title:'Volume 1 — my take choices',url:$('resultLink').value});}catch{}}else $('copy').click();};$('close').onclick=()=>$('shareDialog').close();
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(packet(),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='Volume 1 - Take Review.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('import').onclick=()=>$('file').click();$('file').onchange=async()=>{try{const f=$('file').files[0];if(!f)return;if(f.size>100000)throw Error('Review file too large.');const incoming=validate(JSON.parse(await f.text()));if(Object.keys(decisions).length&&!confirm('Replace this device’s current review choices with this file?'))return;decisions=incoming;save();if(active){$('notes').value=decisions[active.id]?.note||'';renderTakes();}$('saveState').textContent='Review imported. Studio masters are unchanged.';}catch(e){$('saveState').textContent=e.message;}finally{$('file').value='';}};
$('brand').onclick=e=>{e.preventDefault();window.scrollTo({top:0,behavior:'smooth'});};renderSongs();
